### ISSUE TITLE
[feature] Hungarian instructions

### ISSUE THREAD

**Issue by henczati** [luczsoma/HungarianDiceware#1]
IMHO, the **primary audience** for the Hungarian word list **are people who speak Hungarian**.

People who **would benefit the most** from the list are those who do not fully understand the principles and importance of cryptography and strong passwords and **were resistant to** use previous **hard-to-remember alternatives**.

A big part of these people usually have **no or very limited English** knowledge.

**Comment by luczsoma** [comment]
I agree. I will work out a Hungarian version of the PDF and the readme as well.
