### ISSUE TITLE
[feature] Diacritics in the word list

### ISSUE THREAD

**Issue by henczati** [luczsoma/HungarianDiceware#2]
[As Reinhold points out](http://world.std.com/~reinhold/dicewarefaq.html#memory), knowing the meaning of words helps to memorize them. **Knowing the original form** (with diacritics) **is a great aid e.g. during dictionary lookup** of words that have unknown or uncertain meaning to the user, or just look unfamiliar without diacritics.

Using the words without diacritics is then a simple choice left to the user.  **Multiple Hungarian words can have the same form** without diacritics.  To **include only one of these** words in the list allows to keep the strength (entropy) generating from the list when using words without diacritics.

Also, it is **easy to auto-convert** to a diacritic-less form, while the other direction is ambiguous due to the above mentioned reason.

Note, that lists for other languages, e.g. [Czech](http://world.std.com/~reinhold/diceware_wordlist_cz.txt), are also provided with diacritics.

**Comment by luczsoma** [comment]
Thank you for submitting this issue. I was very improvident when creating HungarianDiceware: I do not have the original word list.
